name: Semgrep Test

on:
  pull_request:         # à chaque PR vers n'importe quelle branche
  push:
    branches: [ "main" ]  # et à chaque push sur main

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep (p/ci)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: true
          output: semgrep.sarif

      - name: Upload results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
