name: Semgrep-v2

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]

permissions:
  security-events: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4

      # Génération SARIF
      - name: Run semgrep (SARIF)
        run: |
          semgrep \
            --config=p/comment \
            --config=p/cwe-top-25 \
            --config=p/default \
            --config=p/owasp-top-ten \
            --config=p/r2c-security-audit \
            --config=p/secure-defaults \
            --config=p/javascript \
            --config=p/python \
            --config=p/react \
            --config=p/secrets \
            --config=p/docker-compose \
            --config=p/dockerfile \
            --config=p/bandit \
            --config=p/brakeman \
            --config=p/eslint \
            --config=p/gitleaks \
            --config=p/phpcs-security-audit \
            --config=p/security-code-scan \
            --sarif > semgrep.sarif

      # Patch des severities pour GitHub
      - name: Fix SARIF severities
        run: |
          sed -i 's/"Low"/"2.0"/g' semgrep.sarif
          sed -i 's/"Medium"/"5.0"/g' semgrep.sarif
          sed -i 's/"High"/"8.0"/g' semgrep.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()

      # Génération JSON pour reviewdog
      - name: Run semgrep (JSON)
        run: |
          semgrep \
            --config=p/comment \
            --config=p/cwe-top-25 \
            --config=p/default \
            --config=p/owasp-top-ten \
            --config=p/r2c-security-audit \
            --config=p/secure-defaults \
            --config=p/javascript \
            --config=p/python \
            --config=p/react \
            --config=p/secrets \
            --config=p/docker-compose \
            --config=p/dockerfile \
            --config=p/bandit \
            --config=p/brakeman \
            --config=p/eslint \
            --config=p/gitleaks \
            --config=p/phpcs-security-audit \
            --config=p/security-code-scan \
            --json > semgrep.json

      # Affichage dans la PR via reviewdog
      - name: Report findings with reviewdog
        uses: reviewdog/action-jsonlint@v1
        with:
          reporter: github-pr-review
          level: warning
          json_file: semgrep.json
